Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/mmengine/config/config.py", line 107, in __getattr__
    value = super().__getattr__(name)
  File "/opt/conda/lib/python3.10/site-packages/addict/addict.py", line 67, in __getattr__
    return self.__getitem__(item)
  File "/opt/conda/lib/python3.10/site-packages/mmengine/config/config.py", line 136, in __getitem__
    return self.build_lazy(super().__getitem__(key))
  File "/opt/conda/lib/python3.10/site-packages/mmengine/config/config.py", line 103, in __missing__
    raise KeyError(name)
KeyError: 'output'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/ephemeral/home/JYP/level2-objectdetection-cv-14/mmdetection/train.py", line 68, in <module>
    Gsheet_param(cfg, cfg.output)
  File "/opt/conda/lib/python3.10/site-packages/mmengine/config/config.py", line 1493, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/opt/conda/lib/python3.10/site-packages/mmengine/config/config.py", line 111, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no "
AttributeError: 'ConfigDict' object has no attribute 'output'
